import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-900 text-white">
          <nav className="container mx-auto flex justify-between items-center py-4">
            <div className="logo">
              <a href="#" className="font-bold text-xl">
                My Website
              </a>
            </div>
            <div className="menu">
              <ul className="flex">
                <li>
                  <a href="#" className="px-4 hover:text-gray-400">
                    Home
                  </a>
                </li>
                <li>
                  <a href="#" className="px-4 hover:text-gray-400">
                    About
                  </a>
                </li>
                <li>
                  <a href="#" className="px-4 hover:text-gray-400">
                    Contact
                  </a>
                </li>
              </ul>
            </div>
          </nav>
        </header>
        {/* <div className="min-h-screen"> */}
        <div className="flex min-h-screen p-10">{children}</div>
        <footer className="mt-auto bg-gray-900 text-white">
          <div className="container mx-auto py-8">
            <div className="flex justify-center items-center">
              <a href="#" className="mx-3 hover:text-gray-400">
                <i className="fab fa-facebook fa-lg"></i>
              </a>
              <a href="#" className="mx-3 hover:text-gray-400">
                <i className="fab fa-twitter fa-lg"></i>
              </a>
              <a href="#" className="mx-3 hover:text-gray-400">
                <i className="fab fa-instagram fa-lg"></i>
              </a>
            </div>
            <div className="text-center mt-4">
              <p>&copy; 2023 My Website. All rights reserved.</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
